name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"



[env.production.vars]
GITHUB_ID = "Ov23li7pWIoYccLTsEjh"
GITHUB_OWNER = "ipiecesx"
GITHUB_REPO = "NavSphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://nav.hashmind.cc/api/auth"
NEXT_PUBLIC_API_URL="https://nav.hashmind.cc"

